title: Devlogger
description: Devlogger documentation
theme: just-the-docs

url: https://roblox-devlogger.github.io/
logo: "assets/icons/devlogger2.png"
favicon_ico: "/assets/icons/devlogger.ico"

aux_links:
  Plugin: "https://create.roblox.com/store/asset/17766906953/Devlogger-effortless-and-automated-logging"
