title: Devlogger
description: Devlogger documentation
theme: just-the-docs

url: https://just-the-docs.github.io
logo: "/devlogger2.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
